package com.lancewade.tinyurl.models;


import javax.persistence.*;
import java.util.Date;

@Entity
@Table(name = "longurls")
public class Longurl {

    //Creating id to be autogenerated
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    //Long URL will have a string "url" where we enter the long URL
    private String url;

    //Created and updated at for MySQL. createdAt cannot be updated but updatedAt can.
    @Column(updatable = false)
    private Date createdAt;
    private Date updatedAt;

    //If no created/updated at exist, this will create them.
    @PrePersist
    protected void onCreate() {
        this.createdAt = new Date();
    }
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = new Date();
    }



    public Longurl() {
    }



    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}
